log-dhcp
dhcp-range=10.0.0,proxy
dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:!ipxe,x86PC,"Boot from FOG",undionly.kpxe,10.0.0.10
pxe-service=tag:!ipxe,X86-64_EFI,"Boot from FOG",ipxe.efi,10.0.0.10
interface=YOUR_LAN_INTERFACE
except-interface=lo
except-interface=docker0
dhcp-boot=tag:ipxe,http://10.0.0.10/fog/service/ipxe/boot.php
dhcp-boot=tag:!ipxe,undionly.kpxe,,10.0.0.10
