log-dhcp
dhcp-range=192.168.1.0,proxy
dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:!ipxe,x86PC,"Boot from FOG",undionly.kpxe,192.168.1.132
pxe-service=tag:!ipxe,X86-64_EFI,"Boot from FOG",ipxe.efi,192.168.1.132
interface=eno1
except-interface=lo
except-interface=docker0
dhcp-boot=tag:ipxe,http://192.168.1.132/fog/service/ipxe/boot.php
dhcp-boot=tag:!ipxe,undionly.kpxe,,192.168.1.132
